### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by dotsdl** [omsf/OMSF#22]
It looks like `omsf.io` is currently down. Unclear why at the moment.

**Comment by hvanleeuwen** [comment]
The pages link was not set on master/docs anymore. I changed it back now, but it can take a little while before it is up again. I dont know why the pages link was not set on master/docs anymore.

**Comment by hvanleeuwen** [comment]
I still not coming up, I dont know why. When I run a local install it runs just fine. I could do a force push, but i first would like to know from Karmen if that is ok.

**Comment by hvanleeuwen** [comment]
Here it is back up. I still don't know why the pages link was disabled?

**Comment by karmencj** [comment]
I set up Github Actions workflow to publish docs to a different repo (omsf.github.io) and I disabled it, because the site is now published from that other repo. Something went wrong with GHA, not sure what. Please don't force push!

**Comment by karmencj** [comment]
I made some changes to my gha workflow and in the process, I accidentally used master instead of main in the wrong place. I think I fixed it now, but will do a few more tests. I didn't notice yesterday that I brought the site down with it, that is, it worked when I last checked.

**Comment by karmencj** [comment]
All fixed, I messed up some variable names.
